// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBacoZ2vzVXR0RrXrefVes8zKy0XZYUtZc',
    appId: '1:261546288119:web:313a9fc11b42db2a73c4f2',
    messagingSenderId: '261546288119',
    projectId: 'nards-app',
    authDomain: 'nards-app.firebaseapp.com',
    storageBucket: 'nards-app.appspot.com',
    measurementId: 'G-TTYK96Z33L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSRVq7ISP3Y-En3cM13AEHaLjJElcON1U',
    appId: '1:261546288119:android:dabde549ed7a9a0b73c4f2',
    messagingSenderId: '261546288119',
    projectId: 'nards-app',
    storageBucket: 'nards-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTWFZ83LOcKEJHeOoD4FQGhGXYeFvwjOE',
    appId: '1:261546288119:ios:5c88b0796b33ea9e73c4f2',
    messagingSenderId: '261546288119',
    projectId: 'nards-app',
    storageBucket: 'nards-app.appspot.com',
    iosBundleId: 'com.example.userCafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTWFZ83LOcKEJHeOoD4FQGhGXYeFvwjOE',
    appId: '1:261546288119:ios:5a00fc6feae8092973c4f2',
    messagingSenderId: '261546288119',
    projectId: 'nards-app',
    storageBucket: 'nards-app.appspot.com',
    iosBundleId: 'com.example.userCafe.RunnerTests',
  );
}
